{
	"roomies":[
	{"username":"rao","mail":"kartronics85@yahoo.com"},
	{"username":"iyer","mail":"karthicmystixz@gmail.com"},
	{"username":"sameer","mail":"artoo.in"},
	{"username":"rohit","mail":"kartronics85@gmail.com"}
	],
	"flag":false
}